filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/*.log
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "springboot-logs-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.template.name: "springboot-logs"
setup.template.pattern: "springboot-logs-*"
setup.ilm.enabled: true
setup.ilm.rollover_alias: "springboot-logs"
setup.ilm.pattern: "{now/d}-000001"