info:
  version: 1.0.0
  date: 2025-09-05
  stage: development
  autor: Daniel Arcos
  email: darcos@banred.fin.ec
  description: ms-middleware-signcrypt

server:
  port: ${SERVER_PORT:8442}
  servlet:
    context-path: /api
  compression:
    enabled: true
  error:
    include-message: never
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
  address: 0.0.0.0
  undertow:
    threads:
      io: 10
      worker: 256
    allow-encoded-slash: false
    always-set-keep-alive: true
    decode-url: true
    eager-filter-init: true
    max-cookies: 200
    max-headers: 200
    max-http-post-size: 10MB
    preserve-path-on-forward: false
    url-charset: UTF-8

spring:
  main:
    log-startup-info: true
    banner-mode: console
  thymeleaf:
    enabled: false
  jackson:
    default-property-inclusion: non-null
    serialization:
      write-date-keys-as-timestamps: false
    time-zone: GMT-5
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.banred: DEBUG
    org.springframework.security: DEBUG
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/app.%d{yyyy-MM-dd}.log
      max-history: 7
      total-size-cap: 1GB

camel:
  component:
    servlet:
      enabled: true
    elasticsearch:
      enabled: true
      clusterName: docker-cluster
      hostAddresses: elasticsearch:9200
    saga:
      enabled: false
  springboot:
    main-run-controller: true

microservice:
  parameters:
    REDIS_PORT: ${REDIS_PORT:6379}
    REDIS_USERNAME: ${REDIS_USERNAME:}
    REDIS_PASSWORD: ${REDIS_PASSWORD:}
    REDIS_HOSTNAME: ${REDIS_HOSTNAME:localhost}
    RUTA_CONFIG_XML: ${RUTA_CONFIG_XML:C:/etc/tls/config-service.xml}
    RUTA_CRL: ${RUTA_CRL:certs/ca/crl/crl.der}
