version: '3.8'
 
services:
  redis:
    image: redis:7.2
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
 
volumes:
  redis_data:
    driver: local
