version: "3.9"

services:
  ms-middleware-signcrypt:
    container_name: ms-middleware-signcrypt
    build:
      context: .
      dockerfile: Dockerfile
    image: ms-middleware-signcrypt:1.0.0
    environment:
      - SERVER_PORT=8442
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - RUTA_CONFIG_XML=/etc/tls/config/config-service.xml
      - RUTA_CRL=/etc/tls/certs/ca/crl/crl.der
      - RUTA_RSA=/etc/tls/rsa-keys
      - EXPIRY_SECONDS=300
      - SPRING_JACKSON_DEFAULT_PROPERTY_INCLUSION=non-null
      - SPRING_JACKSON_TIME_ZONE=GMT-5
      - LOGGING_FILE_NAME=/logs/app.log
      - CAMEL_COMPONENT_ELASTICSEARCH_HOSTADDRESSES=elasticsearch:9200
      - REDIS_PASSWORD=
    ports:
      - "8442:8442"
    volumes:
      - ./logs:/logs
      - ./tls/config-service.xml:/etc/tls/config/config-service.xml:ro
      - ./tls/crl/crl.der:/etc/tls/certs/ca/crl/crl.der:ro
      - ./tls/rsa-keys:/etc/tls/rsa-keys:ro
    depends_on:
      - redis
      - elasticsearch
    restart: unless-stopped

  redis:
    image: redis:7.0
    container_name: redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  redis_data:
  es_data:
